collections:
  authors:
    output: true
  courses:
    output: true
  lectures:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"
  - scope:
      path: "_lectures/efficient-algorithms"
      type: "lectures"
    values:
      lecture: "efficient-algorithms"
  - scope:
      path: "_lectures/complexity-theory"
      type: "lectures"
    values:
      lecture: "complexity-theory"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag